// Theme
export const THEME_SET = "THEME_SET";
export const THEMES = {
  DEFAULT: "DEFAULT",
  DARK: "DARK",
  LIGHT: "LIGHT",
  BLUE: "BLUE",
  GREEN: "GREEN",
  INDIGO: "INDIGO",
};

// Auth
export const AUTH_SIGN_IN_REQUEST = "AUTH_SIGN_IN_REQUEST";
export const AUTH_SIGN_IN_SUCCESS = "AUTH_SIGN_IN_SUCCESS";
export const AUTH_SIGN_IN_FAILURE = "AUTH_SIGN_IN_FAILURE";

export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";
export const AUTH_SIGN_UP_REQUEST = "AUTH_SIGN_UP_REQUEST";
export const AUTH_SIGN_UP_SUCCESS = "AUTH_SIGN_UP_SUCCESS";
export const AUTH_SIGN_UP_FAILURE = "AUTH_SIGN_UP_FAILURE";

export const AUTH_RESET_PASSWORD_REQUEST = "AUTH_RESET_PASSWORD_REQUEST";
export const AUTH_RESET_PASSWORD_SUCCESS = "AUTH_RESET_PASSWORD_SUCCESS";
export const AUTH_RESET_PASSWORD_FAILURE = "AUTH_RESET_PASSWORD_FAILURE";

export const PROJECTS_GET_REQUEST = "PROJECTS_GET_REQUEST";
export const PROJECTS_GET_SUCCESS = "PROJECTS_GET_SUCCESS";
export const PROJECTS_GET_FAILURE = "PROJECTS_GET_FAILURE";

export const PROJECTS_ADD_REQUEST = "PROJECTS_ADD_REQUEST";
export const PROJECTS_ADD_SUCCESS = "PROJECTS_ADD_SUCCESS";
export const PROJECTS_ADD_FAILURE = "PROJECTS_ADD_FAILURE";

export const PROJECTS_DELETE_REQUEST = "PROJECTS_DELETE_REQUEST";
export const PROJECTS_DELETE_SUCCESS = "PROJECTS_DELETE_SUCCESS";
export const PROJECTS_DELETE_FAILURE = "PROJECTS_DELETE_FAILURE";

export const RESOURCES_GET_REQUEST = "RESOURCES_GET_REQUEST";
export const RESOURCES_GET_SUCCESS = "RESOURCES_GET_SUCCESS";
export const RESOURCES_GET_FAILURE = "RESOURCES_GET_FAILURE";

export const RESOURCES_ADD_REQUEST = "RESOURCES_ADD_REQUEST";
export const RESOURCES_ADD_SUCCESS = "RESOURCES_ADD_SUCCESS";
export const RESOURCES_ADD_FAILURE = "RESOURCES_ADD_FAILURE";

export const RESOURCES_DELETE_REQUEST = "RESOURCES_DELETE_REQUEST";
export const RESOURCES_DELETE_SUCCESS = "RESOURCES_DELETE_SUCCESS";
export const RESOURCES_DELETE_FAILURE = "RESOURCES_DELETE_FAILURE";
