// Theme
export const THEME_SET = "THEME_SET";
export const THEMES = {
  DEFAULT: "DEFAULT",
  DARK: "DARK",
  LIGHT: "LIGHT",
  BLUE: "BLUE",
  GREEN: "GREEN",
  INDIGO: "INDIGO",
};

// Auth
export const AUTH_SIGN_IN_REQUEST = "AUTH_SIGN_IN_REQUEST";
export const AUTH_SIGN_IN_SUCCESS = "AUTH_SIGN_IN_SUCCESS";
export const AUTH_SIGN_IN_FAILURE = "AUTH_SIGN_IN_FAILURE";

export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";
export const AUTH_SIGN_UP_REQUEST = "AUTH_SIGN_UP_REQUEST";
export const AUTH_SIGN_UP_SUCCESS = "AUTH_SIGN_UP_SUCCESS";
export const AUTH_SIGN_UP_FAILURE = "AUTH_SIGN_UP_FAILURE";

export const AUTH_RESET_PASSWORD_REQUEST = "AUTH_RESET_PASSWORD_REQUEST";
export const AUTH_RESET_PASSWORD_SUCCESS = "AUTH_RESET_PASSWORD_SUCCESS";
export const AUTH_RESET_PASSWORD_FAILURE = "AUTH_RESET_PASSWORD_FAILURE";

export const AUTH_GET_USER_REQUEST = "AUTH_GET_USER_REQUEST";
export const AUTH_GET_USER_SUCCESS = "AUTH_GET_USER_SUCCESS";
export const AUTH_GET_USER_FAILURE = "AUTH_GET_USER_FAILURE";

export const RESOURCES_GET_REQUEST = "RESOURCES_GET_REQUEST";
export const RESOURCES_GET_SUCCESS = "RESOURCES_GET_SUCCESS";
export const RESOURCES_GET_FAILURE = "RESOURCES_GET_FAILURE";

export const RESOURCES_GET_PROJECT_REQUEST = "RESOURCES_GET_PROJECT_REQUEST";
export const RESOURCES_GET_PROJECT_SUCCESS = "RESOURCES_GET_PROJECT_SUCCESS";
export const RESOURCES_GET_PROJECT_FAILURE = "RESOURCES_GET_PROJECT_FAILURE";

export const RESOURCES_ADD_REQUEST = "RESOURCES_ADD_REQUEST";
export const RESOURCES_ADD_SUCCESS = "RESOURCES_ADD_SUCCESS";
export const RESOURCES_ADD_FAILURE = "RESOURCES_ADD_FAILURE";

export const RESOURCES_PATCH_REQUEST = "RESOURCES_PATCH_REQUEST";
export const RESOURCES_PATCH_SUCCESS = "RESOURCES_PATCH_SUCCESS";
export const RESOURCES_PATCH_FAILURE = "RESOURCES_PATCH_FAILURE";

export const RESOURCES_DELETE_REQUEST = "RESOURCES_DELETE_REQUEST";
export const RESOURCES_DELETE_SUCCESS = "RESOURCES_DELETE_SUCCESS";
export const RESOURCES_DELETE_FAILURE = "RESOURCES_DELETE_FAILURE";

export const TASKS_GET_REQUEST = "TASKS_GET_REQUEST";
export const TASKS_GET_SUCCESS = "TASKS_GET_SUCCESS";
export const TASKS_GET_FAILURE = "TASKS_GET_FAILURE";

export const TASKS_GET_PROJECT_REQUEST = "TASKS_GET_PROJECT_REQUEST";
export const TASKS_GET_PROJECT_SUCCESS = "TASKS_GET_PROJECT_SUCCESS";
export const TASKS_GET_PROJECT_FAILURE = "TASKS_GET_PROJECT_FAILURE";

export const TASKS_ADD_REQUEST = "TASKS_ADD_REQUEST";
export const TASKS_ADD_SUCCESS = "TASKS_ADD_SUCCESS";
export const TASKS_ADD_FAILURE = "TASKS_ADD_FAILURE";

export const TASKS_DELETE_REQUEST = "TASKS_DELETE_REQUEST";
export const TASKS_DELETE_SUCCESS = "TASKS_DELETE_SUCCESS";
export const TASKS_DELETE_FAILURE = "TASKS_DELETE_FAILURE";

export const TASKS_PATCH_REQUEST = "TASKS_PATCH_REQUEST";
export const TASKS_PATCH_SUCCESS = "TASKS_PATCH_SUCCESS";
export const TASKS_PATCH_FAILURE = "TASKS_PATCH_FAILURE";

export const WORK_HOURS_CHART_REQUEST = "WORK_HOURS_CHART_REQUEST";
export const WORK_HOURS_CHART_SUCCESS = "WORK_HOURS_CHART_SUCCESS";
export const WORK_HOURS_CHART_FAILURE = "WORK_HOURS_CHART_FAILURE";

export const COSTS_CHART_REQUEST = "COSTS_CHART_REQUEST";
export const COSTS_CHART_SUCCESS = "COSTS_CHART_SUCCESS";
export const COSTS_CHART_FAILURE = "COSTS_CHART_FAILURE";

export const WORK_HOURS_ALL_CHART_REQUEST = "WORK_HOURS_ALL_CHART_REQUEST";
export const WORK_HOURS_ALL_CHART_SUCCESS = "WORK_HOURS_ALL_CHART_SUCCESS";
export const WORK_HOURS_ALL_CHART_FAILURE = "WORK_HOURS_ALL_CHART_FAILURE";

export const COSTS_ALL_CHART_REQUEST = "COSTS_ALL_CHART_REQUEST";
export const COSTS_ALL_CHART_SUCCESS = "COSTS_ALL_CHART_SUCCESS";
export const COSTS_ALL_CHART_FAILURE = "COSTS_ALL_CHART_FAILURE";

export const DAILY_WORK_HOURS_CHART_REQUEST = "DAILY_WORK_HOURS_CHART_REQUEST";
export const DAILY_WORK_HOURS_CHART_SUCCESS = "DAILY_WORK_HOURS_CHART_SUCCESS";
export const DAILY_WORK_HOURS_CHART_FAILURE = "DAILY_WORK_HOURS_CHART_FAILURE";

export const DAILY_WORK_HOURS_ALL_CHART_REQUEST =
  "DAILY_WORK_HOURS_ALL_CHART_REQUEST";
export const DAILY_WORK_HOURS_ALL_CHART_SUCCESS =
  "DAILY_WORK_HOURS_ALL_CHART_SUCCESS";
export const DAILY_WORK_HOURS_ALL_CHART_FAILURE =
  "DAILY_WORK_HOURS_ALL_CHART_FAILURE";

export const RESOURCES_LEVEL_CHART_REQUEST = "RESOURCES_LEVEL_CHART_REQUEST";
export const RESOURCES_LEVEL_CHART_SUCCESS = "RESOURCES_LEVEL_CHART_SUCCESS";
export const RESOURCES_LEVEL_CHART_FAILURE = "RESOURCES_LEVEL_CHART_FAILURE";

export const SKILLS_CHART_REQUEST = "SKILLS_CHART_REQUEST";
export const SKILLS_CHART_SUCCESS = "SKILLS_CHART_SUCCESS";
export const SKILLS_CHART_FAILURE = "SKILLS_CHART_FAILURE";
