export const PROJECTS_GET_REQUEST = "PROJECTS_GET_REQUEST";
export const PROJECTS_GET_SUCCESS = "PROJECTS_GET_SUCCESS";
export const PROJECTS_GET_FAILURE = "PROJECTS_GET_FAILURE";

export const PROJECTS_ADD_REQUEST = "PROJECTS_ADD_REQUEST";
export const PROJECTS_ADD_SUCCESS = "PROJECTS_ADD_SUCCESS";
export const PROJECTS_ADD_FAILURE = "PROJECTS_ADD_FAILURE";

export const PROJECTS_DELETE_REQUEST = "PROJECTS_DELETE_REQUEST";
export const PROJECTS_DELETE_SUCCESS = "PROJECTS_DELETE_SUCCESS";
export const PROJECTS_DELETE_FAILURE = "PROJECTS_DELETE_FAILURE";

export const PROJECTS_PATCH_REQUEST = "PROJECTS_PATCH_REQUEST";
export const PROJECTS_PATCH_SUCCESS = "PROJECTS_PATCH_SUCCESS";
export const PROJECTS_PATCH_FAILURE = "PROJECTS_PATCH_FAILURE";
